### ISSUE TITLE
NodeSecure Next - Vision for the future

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#11]
I think we should deeply discuss the future of NodeSecure in term of ideas and core values. We have already had more or less all together thoughts and ideas. 

The idea is not necessarily to restrict ourselves in our choices to date but rather to establish a more solid foundation to present the project to future collaborators and users.

Some of the core ideas I have in mind:
- Visualization
- Customization
- Neutrality (In the world of security I mean).
- Accessibility ?

I think that these guidelines should come from our project ideas (we should not invent them out of thin air).

**Comment by fraxken** [comment]
In the last meeting we agreed on scheduling a meeting to discuss it.

I think we should plan this in September to be sure no one is in vacation.

**Comment by Kawacrepe** [comment]
I think we missed the 'plan this in september' 🤣 

Also, as Fraxken said on discord, we may want to add a bullet point about:
- how can we work on the dev education?

 @tony-go @antoine-coulon @fraxken

**Comment by fraxken** [comment]
I think we need two hours. So maybe we can schedule this a week-end or at the evening. Beginning of february for example?

**Comment by tony-go** [comment]
Sounds good!

Next week could fit for me

**Comment by im-codebreaker** [comment]
I'm available on weekends and in the evening, so whenever you want.

**Comment by antoine-coulon** [comment]
I'm more likely to be available on evenings

**Comment by Kawacrepe** [comment]
No matter on my side

**Comment by fraxken** [comment]
If the meeting is hold tonight, here is the agenda:

- The project and its evolution (it's the nostalgic moment 😅)
- Core ideas for the NodeSecure org/project as a whole;
    - **Being educational on security** (and open source). Pushing the best practices, writing articles and videos etc...
    - **Neutrality** (we should always promote what's best for developers and end-users, even if it mean doing marketing/communication for third-party initiatives or products as long as they are in line with our values).
    - **Keep engaging** new juniors and experimented contributors (to build a strong and active community).

We must set example on applicating best pratices (that's why the recent work on improving security of our projects is critical).

> **Note** Those ideas/values concerns and impact the collaborators and contributors of each individuals projects.

- Core ideas for NodeSecure packages and tools;
    - Visualization
    - Customization
    - Accessibility
    - **TBC** (discussion between collaborators and contributors required)

- Important projects for 2023 (no orders);
    - CI
    - CLI
    - Authors
    - Database

Continuous improvement of our analysis (back-end) packages is obviously just as critical (JS-X-Ray, Scanner, Vulnera).

---

I distinguished between what was more technical and what was more human.

**Comment by fraxken** [comment]
Meeting record (french): https://www.youtube.com/watch?v=MRNSR35KSF4
