### ISSUE TITLE
Maintenance - Updating build badges

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#17]
Hello 👋 

The build badge is not working anymore on a lot of NodeSecure repositories.

![image](https://user-images.githubusercontent.com/4438263/210713518-83efb4b7-8a07-413e-9eba-e65939cbab07.png)

**This maintenance task is about updating it everywhere.**

Here an example of a valid badge (recently updated on the [JS-X-Ray](https://github.com/NodeSecure/js-x-ray) project):

```
![build](https://img.shields.io/github/actions/workflow/status/NodeSecure/js-x-ray/node.js.yml)
```

This badge has been generated using [shields.io](https://shields.io/). But you can basically copy-paste and only update the repository name (you also need to make sure the workflow file is ok).

## List of impacted repositories

- [x] [Scanner](https://github.com/NodeSecure/scanner)
- [x] [estree-ast-utils](https://github.com/NodeSecure/estree-ast-utils)
- [x] [Vulnera](https://github.com/NodeSecure/vulnera)
- [x] [Github](https://github.com/NodeSecure/github)
- [x] [Gitlab](https://github.com/NodeSecure/gitlab)
- [x] [Domain-check](https://github.com/NodeSecure/domain-check)
- [x] [Sec-literal](https://github.com/NodeSecure/sec-literal)
- [x] [i18n](https://github.com/NodeSecure/i18n)
- [x] [authors](https://github.com/NodeSecure/authors) (**ongoing PR**)
- [x] [ossf-scorecard-sdk](https://github.com/NodeSecure/ossf-scorecard-sdk)
- [x] [size-satisfies](https://github.com/NodeSecure/size-satisfies)
- [x] [flags](https://github.com/NodeSecure/flags)
- [x] [npm-tarball-license-parser](https://github.com/NodeSecure/npm-tarball-license-parser)
- [x] [utils](https://github.com/NodeSecure/utils)
- [x] [fs-walk](https://github.com/NodeSecure/fs-walk)
- [x] [licenses-conformance](https://github.com/NodeSecure/licenses-conformance)
- [x] [report](https://github.com/NodeSecure/report)
- [x] [preview](https://github.com/NodeSecure/preview)

> Feel free to send a pull-request to update the badge

## Missing badge

Some repositories doesn't have the badge at all, please fell free to PR to add it:

- [x] [CI](https://github.com/NodeSecure/ci)
- [x] [RC](https://github.com/NodeSecure/rc)
- [x] [ci-action](https://github.com/NodeSecure/ci-action)
- [x] [vis-network](https://github.com/NodeSecure/vis-network)
- [x] [npm-registry-sdk](https://github.com/NodeSecure/npm-registry-sdk)

**Comment by fabnguess** [comment]
Bonjour @fraxken , je le ferai !

**Comment by fabnguess** [comment]
Bonsoir @fraxken , comme illustré sur l'image, il me semble qu'il manque les actions sur le projet Preview .

![Capture](https://user-images.githubusercontent.com/72697416/211334808-b2917895-6a0b-4988-b147-ed79e94c8222.PNG)

**Comment by fraxken** [comment]
@fabnguess Le flow s'apelle `check.yml` et je viens de mettre en place l'analyse OSSF (n'hésite donc pas quand même à faire ta PR).
