### ISSUE TITLE
Improving the security of the organization

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#18]
Opening an issue to write a bit about the ongoing work to improve the security of the organization.

- [x] Protecting branch on Github (**done**).

# ✅ Security policy

- Adding back a new Security policy (example on the CLI project [here](https://github.com/NodeSecure/cli/blob/master/SECURITY.md)).

# ✅ OpenSSF Scorecards initiative

- Adding the Scorecard Github Action to repositories (see [installation instructions](https://github.com/ossf/scorecard-action#installation)).
- Adding the Scorecard badge to repositories.

# Pin github action (workflows) by commit hash

See https://github.com/NodeSecure/Governance/issues/19

**Comment by antoine-coulon** [comment]
I got this for `ci-action`

**Comment by Kawacrepe** [comment]
Done for `authors`, do you have any ideas about how we can dispatch email to every maintainer?

**Comment by fraxken** [comment]
> do you have any ideas about how we can dispatch email to every maintainer?

My idea was to buy a NodeSecure domain and configure an email (with automatic dispatch to ours personals or pro mail).

**Comment by antoine-coulon** [comment]
Done for `ci-action`, the list seems completed :)
