### ISSUE TITLE
setup ossf scorecard reporting for NodeSecure

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#21]
Hello :wave:

I think it could be cool to configure and use @UlisesGascon [OpenSSF Scorecard Monitor](https://github.com/UlisesGascon/openssf-scorecard-monitor) project to generate a markdown file with all scorecard scores from our org repositories.

See the following ongoing PR for an example: https://github.com/nodejs/security-wg/pull/886 

If anyone would like to contribute and help, please do not hesitate

**Comment by UlisesGascon** [comment]
I will love to do it! 🎉

**Comment by fraxken** [comment]
@UlisesGascon If you want to do it don't hesitate, I was waiting to see if some contributors would take the subject (but no one manifest interest).

**Comment by fraxken** [comment]
@UlisesGascon doesn't seem to work, any idea why ? (I runned the workflow myself).

![image](https://user-images.githubusercontent.com/4438263/226043567-b7216adf-f375-43ff-8e67-28bb87049da4.png)

**Comment by UlisesGascon** [comment]
Let me check, this is the expected output if there are no changes since the last analysis. So there is a bug, I will investigate it

**Comment by UlisesGascon** [comment]
I will do a PR to fix this. There is [typo in the name](https://github.com/NodeSecure/Governance/blob/main/.github/workflows/ossf-scorecard-reporting.yml#L36). This `discovery-orgs: 'nodesecure'` should be the same name as the github login value, in this case `discovery-orgs: 'NodeSecure'`.

The workflow didn't find any scoring for your organization as the OpenSSF Scorecard is case sensitive:
- ✅ https://api.securityscorecards.dev/projects/github.com/NodeSecure/cli
- ❌ https://api.securityscorecards.dev/projects/github.com/nodesecure/cli


Full Debug log, just in case you want to explore it. 

![screencapture-github-UlisesGascon-openssf-scorecard-monitor-demo-actions-runs-4454394530-jobs-7823551149-2023-03-18-09_06_47](https://user-images.githubusercontent.com/5110813/226094297-87f6b67b-cb99-4f09-bc70-76b7228c7965.png)

Note You can always run the Github Action in [Debug mode](https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/), this can provide you a lot of info as I added some debug traces too 👍
