### ISSUE TITLE
How to organize and structure Meetings

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/Governance#7]
The @NodeSecure/core team agreed to organize meetings every two weeks to discuss important subjects related to the project. 

One of the questions of the last meeting is how do we structure those meetings ? One of my idea was to create an issue in this repository for each meeting to be able to prepare some subjects upstream.

This would also inform everyone about the meeting and allow other participants to join if they want.

**Comment by tony-go** [comment]
Yeah, we could filter all issues with the `agenda` label. 🙌 

I have a question: could we filter issues across the organization?
