### ISSUE TITLE
Drop support for Node <= v16

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/Governance#71]
Some packages require Node v16+ ([sometimes even v14](https://github.com/NodeSecure/fs-walk#requirements)).

The idea is to update theses packages with Node v18+ as requirement.
In addition to `README.md`,  `package.json#engines` should be updated (when present):
> ```json
> "engines": {
>  "node": ">=16.0.0"
> },
> ```

CI should also be udpated with v18 + v20:
>  `node-version: [16.x, 18.x]` ->  `node-version: [18.x, 20.x]`
        
## Tools

- [x] [CLI](https://github.com/NodeSecure/cli)
- [x] [scanner](https://github.com/NodeSecure/scanner)
- [x] [JS-X-Ray](https://github.com/NodeSecure/js-x-ray)
- [x] [i18n](https://github.com/NodeSecure/i18n)
- [ ] [vulnera](https://github.com/NodeSecure/vulnera)
- [ ] [CI](https://github.com/NodeSecure/ci)
- [x] [ci-action](https://github.com/NodeSecure/ci-action)
- [x] [RC](https://github.com/NodeSecure/rc)
- [x] [flags](https://github.com/NodeSecure/flags)
- [x] [report](https://github.com/NodeSecure/report)
- [x] [preview](https://github.com/NodeSecure/preview)
- [x] [domain-check](https://github.com/NodeSecure/Domain-check)
- [x] [estree-ast-utils](https://github.com/NodeSecure/estree-ast-utils)
- [x] [Utils](https://github.com/NodeSecure/Utils)
- [x] [fs-walk](https://github.com/NodeSecure/fs-walk)
- [x] [github](https://github.com/NodeSecure/github)
- [x] [gitlab](https://github.com/NodeSecure/gitlab)
- [x] [ossf-scorecard-sdk](https://github.com/NodeSecure/ossf-scorecard-sdk)
- [x] [npm-tarball-license-parser](https://github.com/NodeSecure/npm-tarball-license-parser)
- [x] [licenses-conformance](https://github.com/NodeSecure/licenses-conformance)
- [x] [size-satisfies](https://github.com/NodeSecure/size-satisfies)
- [x] [sec-literal](https://github.com/NodeSecure/sec-literal)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config)
- [x] [npm-registry-sdk](https://github.com/NodeSecure/npm-registry-sdk)
- [x] [npm-security-fetcher](https://github.com/NodeSecure/npm-security-fetcher)
- [x] [authors](https://github.com/NodeSecure/authors)

**Comment by kishore881** [comment]
@fabnguess Node V16 is still mentioned in [Vulnera's Readme](https://github.com/NodeSecure/vulnera#requirements) and one of the workflows [main.yml](https://github.com/NodeSecure/vulnera/blob/main/.github/workflows/main.yml#L23)

**Comment by fabnguess** [comment]
@kishore881  exactly, I'm waiting for Thomas to finish his PR before correcting my PR.

**Comment by fraxken** [comment]
@fabnguess you can finish now I think 😉

**Comment by fabnguess** [comment]
@fraxken, Unless I'm mistaken, the versions of the last two packages have already been raised: EX(https://github.com/NodeSecure/vulnera/blob/26a75919d5f310d90f87a44e6ba4e3e4e0d5faf7/.github/workflows/main.yml#L53)

**Comment by fraxken** [comment]
@fabnguess yep, just need to update README for vulnera I think (i'm closing the issue)
