### ISSUE TITLE
Setup Dependabot groups

### ISSUE THREAD

**Issue by PierreDemailly** [NodeSecure/Governance#92]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

The idea is to setup theses groups:
- GHAs
- deps
- devDeps
- @nodesecure/* only for scanner, cli & ci. Others packages have too few `@nodesecure` dependencies

Some packages have too few dependencies so we can skip them.

## Tools

- [x] [CLI](https://github.com/NodeSecure/cli)
- [x] [scanner](https://github.com/NodeSecure/scanner)
- [x] [JS-X-Ray](https://github.com/NodeSecure/js-x-ray)
- [x] [i18n](https://github.com/NodeSecure/i18n)
- [x] [vulnera](https://github.com/NodeSecure/vulnera)
- [x] [CI](https://github.com/NodeSecure/ci)
- [x] [ci-action](https://github.com/NodeSecure/ci-action) **SKIP** -> GHA 
- [x] [RC](https://github.com/NodeSecure/rc)
- [x] [flags](https://github.com/NodeSecure/flags) **SKIP** -> GHA 
- [x] [report](https://github.com/NodeSecure/report)
- [x] [domain-check](https://github.com/NodeSecure/Domain-check) **SKIP** -> GHA 
- [x] [Utils](https://github.com/NodeSecure/Utils)
- [x] [fs-walk](https://github.com/NodeSecure/fs-walk) **SKIP** -> GHA 
- [x] [github](https://github.com/NodeSecure/github)
- [x] [gitlab](https://github.com/NodeSecure/gitlab)
- [x] [ossf-scorecard-sdk](https://github.com/NodeSecure/ossf-scorecard-sdk)
- [x] [npm-tarball-license-parser](https://github.com/NodeSecure/npm-tarball-license-parser)
- [x] [licenses-conformance](https://github.com/NodeSecure/licenses-conformance)
- [x] [eslint-config](https://github.com/NodeSecure/eslint-config) **SKIP**
- [x] [npm-registry-sdk](https://github.com/NodeSecure/npm-registry-sdk)
- [x] [npm-security-fetcher](https://github.com/NodeSecure/npm-security-fetcher)
- [x] [authors](https://github.com/NodeSecure/authors)

**Comment by fraxken** [comment]
@fabnguess If you have time to handle the 3 last repositories

We need to group at least Github Actions update (for flags I think we should also group devDependencies)
